version: '3.8'
services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=admimadmin
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - ./docker/oracle-db/scripts/startup:/opt/oracle/scripts/startup
