CREATE SEQUENCE C##USER_TEST.PERSON_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE C##USER_TEST.EMAILS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

  CREATE SEQUENCE C##USER_TEST.ADRESSES_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE C##USER_TEST.PHONES_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;